mode: ContinuousDelivery
branches:
  master:
    regex: ^latest$
  pull-request:
    tag: pr
  feature:
    regex: ^features?[/-]
    tag: useBranchName
    increment: Minor
    source-branches: ["master"]
